### ISSUE TITLE
Autonomous DSL proposal

### ISSUE THREAD

**Issue by andrewda** [SouthEugeneRoboticsTeam/sertain#2]
For context, here's an example auto from last season:

```kotlin
suspend fun levelOneToRocketFront(start: AutoMode.StartPosition) {
    val auto = autonomi["Paths"]

    auto.isMirrored = start.location == AutoMode.Location.RIGHT

    try {
        Drivetrain.driveAlongPath(auto["HAB to Rocket Front"], 0.2)

        Drivetrain.alignWithVision(VisionSource.Cargo, true)

        releaseHatchPanel()
    } finally {
        println("Done following path")
    }
}
```

Something like this might be cleaner and remove some boilerplate:

```kotlin
suspend fun levelOneToRocketFront(start: AutoMode.StartPosition) = auto("Paths", start.location == AutoMode.Location.RIGHT) {
	onStart {
		println("Auto is starting")
	}

    sequence {
   		Drivetrain.driveAlongPath(getPath("HAB to Rocket Front"), 0.2)
        Drivetrain.alignWithVision(VisionSource.Cargo, true)
		releaseHatchPanel()
	}

	onComplete {
		println("Done following path")
	}
}
```

**Comment by gnawinganimal** [comment]
This has more or less been done. Now there is
```
doAll {
	action {
		// code
	}
	action {
		// code
	}
}
```
to run actions in parallel, and
```
doOne {
	action {
		// code
	}
	action {
		// code
	}
}
```
to run actions in parallel until one completes, then cancel all others. (Might be helpful, for instance, when logging values until an action completes.)

A sequential block isn't really needed, because that is the default behavior of functions anyway.

There is also `delayForever` and `delayUntil`, for delaying indefinately and delaying until a condition is met.

Another thing that I just thought of that would be nice is a way to delay until an event is fired. Maybe `delayUntil<SomeEvent>()`

Anyway this isn't exactly a DSL because all these functions extend `CoroutineScope` instead of a Class marked as DSL, but this gives you access to suspend functions and coroutines so it's actually a bit more helpful.

**Comment by andrewda** [comment]
Can we add something like `onComplete` which runs after the actions? Maybe also an `onError`, or, alternativity add a `this.status` to `onComplete` which is an enum of "COMPLETE" or "ERROR", for example. This would allow cleanup after an action, whether previous code failed or not.

**Comment by gnawinganimal** [comment]
Great Idea! That might be neater than using `finally`.

**Comment by gnawinganimal** [comment]
Wow August 31 I need to check GitHub more often
