### ISSUE TITLE
Publishing

### ISSUE THREAD

**Issue by gnawinganimal** [SouthEugeneRoboticsTeam/sertain#28]
This should get published. The jar is currently on the JitPack repo, but it can only be downloaded manually (not sure why). Not a huge deal, but preferably we should be able to use the maven coordinates to download it from JitPack.

**Comment by andrewda** [comment]
```gradle
repositories {
	// ...
	maven { url 'https://jitpack.io' }
}

dependencies {
	implementation 'com.github.SouthEugeneRoboticsTeam:sertain:46a38abfe4'
}
```

This doesn't work? Is there an error? What's the full `build.gradle` you're using? Downloading the jar manually is _very_ scary because it can't be version controlled easily (unless you make a gradle script to automatically download the jar and put it in the right place... but then you're just reinventing the wheel since it should already do that). And if it isn't version controlled, you're gonna run into a ton of people using the wrong jar, and it'll quickly become annoying to have to keep downloading the jar for each minor change.

**Comment by gnawinganimal** [comment]
Lol, I have no idea why this wouldnt work. I am doing
```
implementation 'com.github.SouthEugeneRoboticsTeam:sertain:publishing-f3bdecc967-1'
```
in my dependencies, and
```
maven { url 'https://jitpack.io' }
```
in my repositories. If you go to the url, you can install the jar no problem 🤷‍♀

**Comment by andrewda** [comment]
Have you tried `./gradlew clean` and then rebuilding? What is the error you get while building?

**Comment by gnawinganimal** [comment]
Doesn't work. The error is just that it could not find the dependency in the given location `https://jitpack.com`

**Comment by andrewda** [comment]
Huh, I feel like I remember that but completely forget how to fix. Might have been a weird caching thing.

**Comment by gnawinganimal** [comment]
Re-importing and invalidating the caches didn't work either 🤷‍♂ I'm seriously considering putting an issue on jitpack

**Comment by gnawinganimal** [comment]
It worked... no idea why or how. All I did was to add another JitPack dependency, and then it suddenly started working.

**Comment by andrewda** [comment]
Hah, must have jogged its memory.

**Comment by gnawinganimal** [comment]
Yeah, it's working on the `master` branch as well. No idea why, but that wont stop me from being glad about it 😆

**Comment by gnawinganimal** [comment]
I guess this is done
